### ISSUE TITLE
Application still connects over unsecured WebSocket when the "RWA_WEBSOCKET_URL_SSL" is set.

### ISSUE THREAD

**Issue by DROFBOT** [rcon-web-admin/rcon-web-admin#16]
I'm using the docker-image provided by @itzg behind a Nginx reverse-proxy so i can connect to the application over https/wss. However, even when setting the "RWA_WEBSOCKET_URL_SSL" to the appropriate URL, the app still tries to connect over a plain WebSocket, causing the following error in the browser: `The page at 'https://<mydomain>/minecraft/rcon/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://<mydomain>:4327/'. This request has been blocked; this endpoint must be available over WSS.`.

### Docker-compose.yml:
```version: "3.8"
services:
    proxy:
        image: nginx:mainline-alpine
        ports:
            - "80:80"
            - "443:443"
        networks:
            - proxy
        depends_on:
            - minecraft
            - rcon
        restart: always
    minecraft:
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        expose:
            - "25575"
        networks:
            - proxy
        restart: always
        environment:
            EULA: "TRUE"
    rcon:
        image: itzg/rcon
        expose:
            - "4326"
            - "4327"
        volumes:
            - "./volumes/minecraft/rcon:/opt/rcon-web-admin/db"
        networks:
            - proxy
        depends_on:
            - minecraft
        restart: always
        environment: 
            RWA_WEBSOCKET_URL_SSL: "wss://<mydomain>:4327"
networks:
    proxy:
        name: proxy
        driver: "bridge"```

**Comment by DROFBOT** [comment]
I managed to find a workaround by adding a `config.js` file to the container based on the template in this repo. This is a fragile solution however, as the mapped path in the container contains the version number.

### Docker-compose.yml
```
services:
    proxy:
        image: nginx:mainline-alpine
        ports:
            - "80:80"
            - "443:443"
        networks:
            - proxy
        depends_on:
            - minecraft
            - rcon
        restart: always
    minecraft:
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        expose:
            - "25575"
        networks:
            - proxy
        restart: always
        environment:
            EULA: "TRUE"
    rcon:
        image: itzg/rcon
        expose:
            - "4326"
            - "4327"
        volumes:
            - "./volumes/minecraft/rcon:/opt/rcon-web-admin/db"
            - type: bind
              source: ./volumes/rcon/config.js
              target: /opt/rcon-web-admin-0.14/config.js
        networks:
            - proxy
        depends_on:
            - minecraft
        restart: always
networks:
    proxy:
        name: proxy
        driver: "bridge"
```

### config.js
```
"use strict";

/**
 * User configuration
 * Copy to config.js to enable it
 */
var config = {
    /**
     * The host to bind the webinterface to
     * null if you want allow every hostname
     */
    "host": null,

    /**
     * The full wss:// url to the websocket
     * Null if default, only required to change when you proxy your application
     */
    "websocketUrlSsl": "wss://<mydomain>/minecraft/rcon/websocket:80",

    /**
     * The full ws://
     * Null if default, only required to change when you proxy your application
     */
    "websocketUrl": "ws://<mydomain>/minecraft/rcon/websocket:80",

    /**
     * The port for the server and websocket
     * The given number is the one for the webinterface
     * The given number + 1 is the websocket port
     * Notice that both given number and the number+1 will be required
     */
    "port": 80
};

module.exports = config;
```
